alias ls='ls --color=auto'
alias ll='ls -al'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'

alias cppinit='~/dev/cpp-template/clone.sh'
alias cppbuild='~/dev/cpp-template/build.sh'
alias cpprun='~/dev/cpp-template/run.sh'

alias nvide='(nvim --headless --listen localhost:6666 &) && neovide.exe --server localhost:6666'

alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# Git aliases (replaces ohmyzsh/git plugin)
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcam='git commit -a -m'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gl='git log --oneline --decorate --graph'
alias gp='git pull'
alias gP='git push'
alias gst='git status'
alias gsw='git switch'
alias gswc='git switch -c'
